# Generated by Django 5.2.8 on 2025-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_deposit_amount_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('buche', 'Buche'), ('pain', 'Pain'), ('autre', 'Autre')], default='buche', max_length=20),
        ),
    ]
