# Generated by Django 5.2.8 on 2025-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('buche', 'Buche'), ('pain', 'Pain'), ('autre', 'Autre'), ('patisserie', 'Pâtisserie'), ('viennoiserie', 'Viennoiserie')], default='autre', max_length=20),
        ),
    ]
